#!/usr/bin/env php
<?php
/**
 * XLS 2 MODX : Excel Import Utility
 *
 *
 * USAGE
 * -------
 *
 * php xls2modx <function> [arguments]
 *
 * php xls2modx help [function-name]
 *
 */
ini_set('max_execution_time', 0);

require_once dirname(__FILE__).'/vendor/autoload.php';

use Xls2modx\Console\Command\ImportCommand;
use Xls2modx\Console\Command\ExportCommand;
use Xls2modx\Console\Command\MapExportCommand;
use Xls2modx\Console\Command\MapImportCommand;
use Xls2modx\Console\Command\MapImportWpCommand;


use Symfony\Component\Console\Application;

$application = new Application('xls2modx', '1.0');

$application->add(new ImportCommand());
$application->add(new ExportCommand());
$application->add(new MapImportCommand());
$application->add(new MapImportWpCommand());
$application->add(new MapExportCommand());
$application->run();

/*EOF*/