#!/usr/bin/env php
<?php
/**
 * XLS 2 MODX : Excel Import Utility
 *
 *
 * USAGE
 * -------
 *
 * php xls2modx <function> [arguments]
 *
 * php modxbackup help [function-name]
 *
 */
require_once dirname(__FILE__).'/vendor/autoload.php';

use Xls2modx\Console\Command\ImportCommand;
use Xls2modx\Console\Command\MapCommand;


use Symfony\Component\Console\Application;

$application = new Application('xls2modx', '1.0');

$application->add(new ImportCommand());
$application->add(new MapCommand());
$application->run();

/*EOF*/